  version: '3'
  networks:
    laravel:
  services:

    webserver:
      image: nginx:1.18.0
      container_name: webserver
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./vannak.jr:/var/www/html
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app
      networks:
        - laravel
    app:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      image: putheakhem.com/php
      container_name: app
      restart: unless-stopped
      tty: true
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www/html
      volumes:
        - ./vannak.jr:/var/www/html
        - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
        - laravel

    db:
      image: mysql:5.7.22
      container_name: db
      restart: unless-stopped
      tty: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_USER: root
        MYSQL_PASSWORD: dockerlaravel
        MYSQL_ROOT_PASSWORD: dockerlaravel
        SERVICE_TAGS: dev
        SERVICE_NAME: db
      volumes:
        - mysql_data:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      networks:
        - laravel
  volumes:
    mysql_data:
      driver: local



